### ISSUE TITLE
Stops working on /reload

### ISSUE THREAD

**Issue by BigPhobos** [navneetset/pebbles-cobblemon-spawnrate-modifier#1]
**Mod Jar:** CTGSB 1.0.0-1.20.1 (Fabric)
**Server Jar:** Fabric Loader 0.15.9-1.20.1

1) Install mod on server
2) Use /reload
3) CTGSB commands no longer function

**Comment by navneetset** [comment]
/reload will break a lot of mods. It is not supported, and does nothing for the mod. /reload also breaks some part of fCobblemon so please do not use the command.
